'use client';

import { useState, useEffect } from 'react';
import AuthGuard from '@/components/auth/AuthGuard';
import DashboardLayout from '@/components/layout/DashboardLayout';
import { supabase } from '@/lib/supabase';
import type { Member, Profile } from '@/types';

interface MemberFormData {
  profile_id: string;
  full_name: string;
  phone: string;
  address: string;
  currency: 'USD' | 'HTG';
  status: 'active' | 'inactive' | 'suspended';
  default_password: string;
}

export default function AdminMembersPage() {
  const [members, setMembers] = useState<Member[]>([]);
  const [profiles, setProfiles] = useState<Pick<Profile, 'id' | 'email' | 'full_name' | 'role' | 'approved'>[]>([]);
  const [loading, setLoading] = useState(true);
  const [isAdmin, setIsAdmin] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [formData, setFormData] = useState<MemberFormData>({
    profile_id: '',
    full_name: '',
    phone: '',
    address: '',
    currency: 'HTG',
    status: 'active',
    default_password: '',
  });

  useEffect(() => {
    const checkAdmin = async () => {
      try {
        const { data: { user }, error: authError } = await supabase.auth.getUser();
        if (authError || !user) {
          setIsAdmin(false);
          setLoading(false);
          return;
        }

        const { data: profile, error: profileError } = await supabase
          .from('profiles')
          .select('role')
          .eq('id', user.id)
          .maybeSingle();

        if (profileError) {
          console.error('Profile error:', profileError);
          setIsAdmin(false);
          setLoading(false);
          return;
        }

        setIsAdmin(profile?.role === 'admin');
        setLoading(false);
      } catch (err) {
        console.error('Error checking admin:', err);
        setIsAdmin(false);
        setLoading(false);
      }
    };

    checkAdmin();
  }, []);

  useEffect(() => {
    if (isAdmin) {
      loadMembers();
      loadProfiles();
    }
  }, [isAdmin]);

  const loadMembers = async () => {
    try {
      const { data, error: fetchError } = await supabase
        .from('members')
        .select('*')
        .order('created_at', { ascending: false });

      if (fetchError) {
        console.error('Error fetching members:', fetchError);
        setError('Erreur lors du chargement des membres');
        return;
      }

      setMembers(data || []);
    } catch (err) {
      console.error('Error loading members:', err);
      setError('Erreur lors du chargement des membres');
    }
  };

  const loadProfiles = async () => {
    try {
      // Load profiles that don't have a member record yet
      const { data: allProfiles, error: profilesError } = await supabase
        .from('profiles')
        .select('id, email, full_name, role, approved')
        .eq('approved', true)
        .order('full_name');

      if (profilesError) {
        console.error('Error fetching profiles:', profilesError);
        return;
      }

      // Get profiles that already have members
      const { data: existingMembers } = await supabase
        .from('members')
        .select('profile_id');

      const existingProfileIds = new Set(
        (existingMembers || []).map(m => m.profile_id)
      );

      // Filter out profiles that already have members
      const availableProfiles = (allProfiles || []).filter(
        p => !existingProfileIds.has(p.id)
      );

      setProfiles(availableProfiles);
    } catch (err) {
      console.error('Error loading profiles:', err);
    }
  };

  const handleInputChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setSuccess(null);
    setSubmitting(true);

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Utilisateur non connecté');

      if (!formData.profile_id) {
        throw new Error('Veuillez sélectionner un profil utilisateur');
      }

      if (!formData.full_name.trim()) {
        throw new Error('Le nom complet est requis');
      }

      if (!formData.default_password || formData.default_password.length < 6) {
        throw new Error('Le mot de passe par défaut doit contenir au moins 6 caractères');
      }

      // Create member - member_id will be auto-generated by trigger
      const { data, error: insertError } = await supabase
        .from('members')
        .insert({
          profile_id: formData.profile_id,
          full_name: formData.full_name.trim(),
          phone: formData.phone.trim() || null,
          address: formData.address.trim() || null,
          currency: formData.currency,
          status: formData.status,
          is_default_password: true, // Mark as default password
        })
        .select()
        .maybeSingle();

      if (insertError || !data) {
        console.error('Insert error:', insertError);
        throw new Error(insertError?.message || 'Erreur lors de la création du membre');
      }

      // Create auth user with default password using technical email system
      const memberIdClean = data.member_id.replace(/-/g, '').trim();
      const technicalEmail = `${memberIdClean}@members.tikredi.ht`;
      
      // Create auth user account using technical email
      const { data: signUpData, error: signUpError } = await supabase.auth.signUp({
        email: technicalEmail,
        password: formData.default_password,
        options: {
          data: {
            full_name: formData.full_name.trim(),
            member_id: data.member_id,
            true_email: null, // Admin-created members don't have email yet
          },
        },
      });

      if (signUpError) {
        console.error('SignUp error:', signUpError);
        // Delete the member if auth creation failed
        await supabase.from('members').delete().eq('id', data.id);
        
        // Provide more specific error message
        let errorMessage = 'Erreur lors de la création du compte.';
        if (signUpError.message?.includes('already registered') || signUpError.message?.includes('already exists')) {
          errorMessage = `Un compte existe déjà avec cet ID (${memberIdClean}). Veuillez utiliser un autre numéro de membre.`;
        } else {
          errorMessage = `Erreur lors de la création du compte: ${signUpError.message || 'Erreur inconnue'}`;
        }
        throw new Error(errorMessage);
      }

      if (signUpData.user) {
        // Update member to link profile_id to the new user
        await supabase
          .from('members')
          .update({ 
            profile_id: signUpData.user.id,
            password_set: true 
          })
          .eq('id', data.id);

        // Ensure profile exists and is linked
        await supabase
          .from('profiles')
          .upsert({
            id: signUpData.user.id,
            email: null, // Technical email is stored in auth.users, not in profiles
            full_name: formData.full_name.trim(),
            role: 'member',
            approved: true, // Auto-approve members created by admin
          }, {
            onConflict: 'id',
          });
      }
      
      setSuccess(`Membre créé avec succès! Numéro: ${data.member_id}. Le membre peut se connecter avec son numéro (${data.member_id.replace(/-/g, '')}) et le mot de passe par défaut. Il devra changer son mot de passe lors de sa première connexion.`);
      setFormData({
        profile_id: '',
        full_name: '',
        phone: '',
        address: '',
        currency: 'HTG',
        status: 'active',
        default_password: '',
      });
      setShowForm(false);
      await loadMembers();
      await loadProfiles();
    } catch (err) {
      console.error('Error creating member:', err);
      setError(err instanceof Error ? err.message : 'Erreur lors de la création du membre');
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <AuthGuard>
        <DashboardLayout>
          <div className="flex items-center justify-center min-h-screen">
            <div className="text-center">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto"></div>
              <p className="mt-4 text-gray-600">Chargement...</p>
            </div>
          </div>
        </DashboardLayout>
      </AuthGuard>
    );
  }

  if (!isAdmin) {
    return (
      <AuthGuard>
        <DashboardLayout>
          <div className="bg-red-50 border border-red-200 rounded-lg p-6">
            <h2 className="text-xl font-bold text-red-800 mb-2">Accès refusé</h2>
            <p className="text-red-600">
              Vous devez être administrateur pour accéder à cette page.
            </p>
          </div>
        </DashboardLayout>
      </AuthGuard>
    );
  }

  return (
    <AuthGuard>
      <DashboardLayout>
        <div className="space-y-6">
          {/* Header */}
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Gestion des Membres</h1>
              <p className="text-gray-600 mt-2">
                Créez et gérez les membres de la mutuelle
              </p>
            </div>
            <button
              onClick={() => setShowForm(!showForm)}
              className="bg-primary text-white px-6 py-3 rounded-lg hover:bg-primary-dark transition-colors font-semibold"
            >
              {showForm ? 'Annuler' : '+ Créer un Membre'}
            </button>
          </div>

          {/* Success/Error Messages */}
          {success && (
            <div className="bg-green-50 border border-green-200 rounded-lg p-4">
              <p className="text-green-600">{success}</p>
            </div>
          )}

          {error && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-4">
              <p className="text-red-600">{error}</p>
            </div>
          )}

          {/* Create Member Form */}
          {showForm && (
            <div className="bg-white rounded-lg shadow-md p-6">
              <h2 className="text-xl font-bold text-gray-900 mb-4">Créer un Nouveau Membre</h2>
              <form onSubmit={handleSubmit} className="space-y-4">
                {/* Profile Selection */}
                <div>
                  <label htmlFor="profile_id" className="block text-sm font-medium text-gray-700 mb-2">
                    Utilisateur <span className="text-red-500">*</span>
                  </label>
                  <select
                    id="profile_id"
                    name="profile_id"
                    value={formData.profile_id}
                    onChange={handleInputChange}
                    required
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                  >
                    <option value="">Sélectionnez un utilisateur</option>
                    {profiles.map((profile) => (
                      <option key={profile.id} value={profile.id}>
                        {profile.full_name || profile.email} ({profile.email})
                      </option>
                    ))}
                  </select>
                  {profiles.length === 0 && (
                    <p className="text-sm text-gray-500 mt-1">
                      Tous les utilisateurs approuvés ont déjà un membre associé.
                    </p>
                  )}
                </div>

                {/* Full Name */}
                <div>
                  <label htmlFor="full_name" className="block text-sm font-medium text-gray-700 mb-2">
                    Nom Complet <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    id="full_name"
                    name="full_name"
                    value={formData.full_name}
                    onChange={handleInputChange}
                    required
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                    placeholder="Jean Dupont"
                  />
                </div>

                {/* Phone */}
                <div>
                  <label htmlFor="phone" className="block text-sm font-medium text-gray-700 mb-2">
                    Téléphone
                  </label>
                  <input
                    type="tel"
                    id="phone"
                    name="phone"
                    value={formData.phone}
                    onChange={handleInputChange}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                    placeholder="+50912345678"
                  />
                </div>

                {/* Address */}
                <div>
                  <label htmlFor="address" className="block text-sm font-medium text-gray-700 mb-2">
                    Adresse
                  </label>
                  <textarea
                    id="address"
                    name="address"
                    value={formData.address}
                    onChange={handleInputChange}
                    rows={3}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                    placeholder="Port-au-Prince, Haiti"
                  />
                </div>

                {/* Currency */}
                <div>
                  <label htmlFor="currency" className="block text-sm font-medium text-gray-700 mb-2">
                    Devise <span className="text-red-500">*</span>
                  </label>
                  <select
                    id="currency"
                    name="currency"
                    value={formData.currency}
                    onChange={handleInputChange}
                    required
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                  >
                    <option value="HTG">HTG (Gourde Haïtienne) - Code: 02</option>
                    <option value="USD">USD (Dollar US) - Code: 01</option>
                  </select>
                  <p className="text-sm text-gray-500 mt-1">
                    Le numéro de membre sera généré au format: YY-SEQUENCE-CODE
                    <br />
                    Exemple: 25-00001-01 (USD) ou 25-00001-02 (HTG)
                  </p>
                </div>

                {/* Status */}
                <div>
                  <label htmlFor="status" className="block text-sm font-medium text-gray-700 mb-2">
                    Statut <span className="text-red-500">*</span>
                  </label>
                  <select
                    id="status"
                    name="status"
                    value={formData.status}
                    onChange={handleInputChange}
                    required
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                  >
                    <option value="active">Actif</option>
                    <option value="inactive">Inactif</option>
                    <option value="suspended">Suspendu</option>
                  </select>
                </div>

                {/* Default Password */}
                <div>
                  <label htmlFor="default_password" className="block text-sm font-medium text-gray-700 mb-2">
                    Mot de passe par défaut <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="password"
                    id="default_password"
                    name="default_password"
                    value={formData.default_password}
                    onChange={handleInputChange}
                    required
                    minLength={6}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                    placeholder="Minimum 6 caractères"
                  />
                  <p className="mt-1 text-sm text-gray-500">
                    Le membre devra changer ce mot de passe lors de sa première connexion
                  </p>
                </div>

                {/* Submit Button */}
                <div className="flex justify-end space-x-4 pt-4">
                  <button
                    type="button"
                    onClick={() => setShowForm(false)}
                    className="px-6 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 transition-colors"
                  >
                    Annuler
                  </button>
                  <button
                    type="submit"
                    disabled={submitting}
                    className="px-6 py-2 bg-primary text-white rounded-lg hover:bg-primary-dark transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {submitting ? 'Création...' : 'Créer le Membre'}
                  </button>
                </div>
              </form>
            </div>
          )}

          {/* Members List */}
          <div className="bg-white rounded-lg shadow-md overflow-hidden">
            <div className="px-6 py-4 border-b border-gray-200">
              <h2 className="text-xl font-bold text-gray-900">Liste des Membres</h2>
              <p className="text-sm text-gray-600 mt-1">
                {members.length} membre{members.length !== 1 ? 's' : ''} au total
              </p>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Numéro
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Nom
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Téléphone
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Devise
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Statut
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Date d&apos;adhésion
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {members.length === 0 ? (
                    <tr>
                      <td colSpan={6} className="px-6 py-8 text-center text-gray-500">
                        Aucun membre trouvé
                      </td>
                    </tr>
                  ) : (
                    members.map((member) => (
                      <tr key={member.id} className="hover:bg-gray-50">
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className="font-mono font-semibold text-primary">
                            {member.member_id}
                          </span>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm font-medium text-gray-900">
                            {member.full_name}
                          </div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                          {member.phone || '-'}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className={`px-2 py-1 text-xs font-semibold rounded-full ${
                            member.currency === 'USD'
                              ? 'bg-blue-100 text-blue-800'
                              : 'bg-green-100 text-green-800'
                          }`}>
                            {member.currency}
                          </span>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className={`px-2 py-1 text-xs font-semibold rounded-full ${
                            member.status === 'active'
                              ? 'bg-green-100 text-green-800'
                              : member.status === 'inactive'
                              ? 'bg-gray-100 text-gray-800'
                              : 'bg-red-100 text-red-800'
                          }`}>
                            {member.status === 'active' ? 'Actif' :
                             member.status === 'inactive' ? 'Inactif' : 'Suspendu'}
                          </span>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                          {new Date(member.join_date).toLocaleDateString('fr-FR')}
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </DashboardLayout>
    </AuthGuard>
  );
}

